### PR TITLE
handle List ItemType in the spec file

### PR DESCRIPTION
**Pull request by Guslington**
Issue #474

### CODE REVIEW

**Comment by gergnz** [comment]
Thanks for this @Guslington . Do you mind fixing up the rubocop error.

https://app.travis-ci.com/github/cfndsl/cfndsl/jobs/570082658

I'm happy for you to just put an override above that method.

**Comment by Guslington** [comment]
@gergnz rubocop errors resolved

**Comment by gergnz** [comment]
Thanks @Guslington. Merged, give me a bit of time (I'll try to get to it today) to do a release.

**Comment by Guslington** [comment]
Thanks @gergnz 😃

**Pull request merged**
