### PR TITLE
Update the embedded resource specification file to version 1.9.1

### PR DESCRIPTION
**Pull request by bobziuchkovski**
The Cloudformation spec file bundled with cfndsl is outdated.  The bundled version is v1.3.1 whereas the latest published version is v1.9.1.  Update the bundled revision to v1.9.1.

I realize people can run `cfndsl -u` to pull the latest revision themselves, but given the spec file is sometimes updated with erroneous values (see https://github.com/stevenjack/cfndsl/pull/345), it's probably helpful to bump the embedded spec periodically since it guarantees a known-working state.

Note that this actually depends on https://github.com/stevenjack/cfndsl/pull/345 or else cfndsl will error when trying to parse the spec file.

### CODE REVIEW

**Comment by bobziuchkovski** [comment]
The Travis build failed because the updated spec relies on the patch from https://github.com/stevenjack/cfndsl/pull/345.

**Comment by ans0600** [comment]
@bobziuchkovski My previous attempt has been rejected. See the reason here: https://github.com/stevenjack/cfndsl/pull/339

**Comment by bobziuchkovski** [comment]
@ans0600 Reading that PR's comments, it didn't seem like it was rejected.  It sounded like the advice was simply that any corrections to the spec file might need to be added to `lib/cfndsl/patches.rb` (as https://github.com/stevenjack/cfndsl/pull/345 does), and to raise the issue with AWS support if any such patches are needed.  Regarding the latter, I just opened a support case with the AWS CloudFormation team to inform them of the error that #345 addresses.

**Comment by bobziuchkovski** [comment]
AWS support got back to me about the bogus AWS::SSM::PatchBaseline.PatchGroup type.  The service team has released an updated resource specification file that addresses the issue.

I've updated this PR with that fixed resource specification file.

However, this exposed a new problem: the AutoScalingGroup `Tags` property has been [renamed](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-tags) to `AsTags` in CloudFormation.  This is causing the Travis build to fail because `ResourceDefinition#add_tag` was mixing and matching handling of the two different tag types.  I've posted a separate PR to fix that problem as well: https://github.com/stevenjack/cfndsl/pull/350.  If #350 is merged, then I can rebase this PR and it will be green as well.

**Comment by bobziuchkovski** [comment]
Just to follow-up on this, the AutoScalingGroup `Tags` -> `AsTags` change appears to be an error in both the official documentation and the resource specification file.  I've reached out to AWS support about the new error and they responded confirming the problem and have dispatched to the CloudFormation service team.

This PR shouldn't be merged yet...we'll need to wait until they fix the latest resource spec file and update/test again.  I'll post back when this happens.

**Comment by bobziuchkovski** [comment]
@gergnz There's a new 1.9.1 spec revision out and it looks like it addresses all of the problems we've seen thus far.  It removes the bogus `AWS::SSM::PatchBaseline.PatchGroup` property type, it has the correct `Tags` property for `AWS::AutoScaling::AutoScalingGroup`, and it doesn't appear to be missing any resource types.

I've updated this PR to include this latest 1.9.1 resource spec revision, which now passes all specs.

I've tested it against our myriad CFN templates we use to ensure the templates render the same JSON now as they did before, and have also used jq to sort and diff ResourceTypes and PropertyTypes keys.  This time I see only addition of new properties -- not bogus removal of anything.

All in all, it finally looks like a sane spec release.  😄  I think this is now safe to merge.

**Comment by gergnz** [comment]
Thanks for tracking this @bobziuchkovski. I've created usertesting#1 to remove some of the patches we had for the old specification included. This removes the requirements to have those. If you can pull that through, I'll merge this. 👍

**Comment by bobziuchkovski** [comment]
@gergnz Done -- thanks!

**Pull request merged**
