### PR TITLE
use the gzip file instead as it's much faster on the wire Fixes #394

### LINKED ISSUE #394: confirm we are using gzip download of cloudfomration specification.

### PR DESCRIPTION
**Pull request by gergnz**

### CODE REVIEW

**Comment by blofeldthefish** [comment]
This change has been applied to #395.

**Comment by johnf** [comment]
Should we update ```CHANGELOG.md``` with each PR, or do we just collect everything when we release?

**Comment by gergnz** [comment]
> Should we update `CHANGELOG.md` with each PR, or do we just collect everything when we release?

Changelog gets updated automatically when we tag/release:

https://github.com/cfndsl/cfndsl/blob/master/Rakefile#L50-L52

**Comment by gergnz** [comment]
Merged in #395

**Pull request closed without merging**
