### PR TITLE
fix bugs in rake task

### PR DESCRIPTION
**Pull request by lwoggardner**
multiple extras files
  remove ruby tags from yaml output

### CODE REVIEW

**Comment by gergnz** [comment]
Thanks @lwoggardner. I'll merge this and #452 and release 1.0.4

**Comment by lwoggardner** [comment]
Thanks - what's involved in a release? and is there an ETA?

**Comment by gergnz** [comment]
> Thanks - what's involved in a release? and is there an ETA?

Sorry, It's been a crazy week (world)... Releasing 1.0.5 now. (1.0.4 exploded by the looks on my laptop and I had just assumed it worked.)

**Comment by lwoggardner** [comment]
Thanks. I might explore some gitops goodness to track the spec.

**Pull request merged**
