### PR TITLE
fixes #389 in master

### LINKED ISSUE #389: ArtifactStore and ArtifactStores are not the same thing
similar to #380 and #354 

This is actually 2 different Properties in AWS::CodePipeline::Pipeline.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html

### PR DESCRIPTION
**Pull request by gergnz**
Fixes #389

### CODE REVIEW

**Comment by gergnz** [comment]
ping @lwoggardner

**Comment by lwoggardner** [comment]
Is there someone you can add a test for this case ?  Otherwise looks fine to me (if that's what you are asking).

**Comment by gergnz** [comment]
> Is there somewhere you can add a test for this case ? Otherwise looks fine to me (if that's what you are asking).

@lwoggardner the issue is this patch conflicts with your patch. https://travis-ci.org/cfndsl/cfndsl/builds/484971538

The pluralisation is confusing because AWS Cloudformation uses pluralisation for different types of data.

I'm almost wondering if we should remove pluralisation altogether.

**Comment by gergnz** [comment]
Now I'm confused.

Example code:
```
# frozen_string_literal: true

require 'cfndsl'

CloudFormation do
  Description 'Pipeline'

  CodePipeline_Pipeline(:pipeline) do
    ArtifactStore(
      Location: 'mybucket',
      Type: 'S3'
    )
  end
end
```

In master produces `cfndsl -b x.rb`:
```
{"AWSTemplateFormatVersion":"2010-09-09","Description":"Pipeline","Resources":{"pipeline":{"Properties":{"ArtifactStores":[{"Location":"mybucket","Type":"S3"}]},"Type":"AWS::CodePipeline::Pipeline"}}}
```

If I put this test in master:
```
    it 'check ArtifactStore is a hash' do
      template.CodePipeline_Pipeline(:Test) do
        ArtifactStore(
          Location: 'mybucket',
          Type: 'S3'
        )
      end

      expect(template.to_json).to include('"ArtifactStore":{"Location":"mybucket","Type":"S3"}')
      expect(template.to_json).not_to include('"ArtifactStores":{"Location":"mybucket","Type":"S3"}')
      expect(template.to_json).not_to include('"ArtifactStores":[{"Location":"mybucket","Type":"S3"}]')
    end
```

I get:
```
{"AWSTemplateFormatVersion":"2010-09-09","Resources":{"Test":{"Properties":{"ArtifactStore":{"Location":"mybucket","Type":"S3"}},"Type":"AWS::CodePipeline::Pipeline"}}}```

Which is correct.

In this branch both work as expected.

Why is there a difference?

**Comment by gergnz** [comment]
With the tests for the plural of ArtifactStore, (ArtifactStores) it now fails. This plural stuff really is confusing if we are trying to deal with all the oddities of how Cloudformation does plurals

**Pull request closed without merging**
